language: python

env:
  - PIP_USE_MIRRORS=true
python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get install cython python-dev
  - pip install coverage coveralls

script: 
  - ./travis-ci.sh

after_success: 
  - coveralls