language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get install cython python-nose python-dev python-coverage python-pip
  - sudo pip install coveralls

script: 
  - ./travis-ci.sh