language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update

install:
  - sudo apt-get install cython python-nose python-dev
  - pip install cython --use-mirrors

script: "make test"